writer_name: "lstm"
train_path: "/home/song/git/sentencepunc/data/final_data/as.train"
train_num: "/home/song/git/sentencepunc/data/final_data/as.train.num"
dev_path: "/home/song/git/sentencepunc/data/final_data/as.valid"
dev_num: "/home/song/git/sentencepunc/data/final_data/as.valid.num"
vocab_path: "/home/song/git/sentencepunc/data/final_data/as.vocab"
log_path: "/larch/song/experiment/sentencepunc/log/"
#model_path: "/larch/song/shinjin2019/train_log/base_test/base_test_5.pt"
model_path: "/larch/song/experiment/sentencepunc/model/"
result_path: "/larch/song/experiment/sentencepunc/result/"
device: "cuda"
epoch: 7 
method: "base"
lr: 0.0003
batch_size: 256 
emb_size: 512
hidden_size: 512
encoder_layer_num: 3
dropout_rate: 0.2
save_iter: 1
dev_per_iter: 20 
load_iter: 4
